language: python
python:
  - "3.8"
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --add channels conda-forge
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda

  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pygraphblas pytest
  - conda activate test-environment
  - sudo apt update
  - sudo apt-get install -y antlr4;
  - pip install -r requirements.txt

script:
  - cd src/antlr && antlr4 -Dlanguage=Python3 DbQLGrammar.g4 
  - cd ../../
  - python -m pytest